# 1.1 Numpy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
tools for integrating C/C++ and Fortran code
useful linear algebra, Fourier transform, and random number capabilities
Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

##### Source: http://www.numpy.org/

In [3]:
import numpy as np

# Why use numpy?

In [4]:
a = [[2,5],[7,9]]
a.mean()

In [5]:
a = np.array([[2,5],[7,9]])
a.

In [6]:
%%time
soma = 0

for i in range(0,10000001):
    soma = soma + i

Wall time: 5.2 s


In [7]:
%%time

soma = np.arange(0,10000001).sum()

Wall time: 196 ms


### Data types

In [56]:
x = np.float32(1.0)
y = np.int_([1,2,4])
z = np.arange(3, dtype=np.uint8)

print(x)
print(y)
print(z)

z.astype(float) 

1.0
[1 2 4]
[0 1 2]


array([0., 1., 2.])

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [9]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                    


data = np.fenfromtxt("file.csv")  # import from file

(2, 3)


In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              

b = np.ones((1,2))    # Create an array of all ones
print(b)             

c = np.full((2,2), 7)  # Create a constant array
print(c)               

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              

e = np.random.random((2,2))  # Create an array filled with random values
print(e)

### Slicing Arrays

In [10]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
a[:2,1:3]

array([[2, 3],
       [6, 7]])

### Boolean Arrays

In [16]:
a = np.array([[1,2], [3, 4], [5, 6]])

#bool_idx = (a > 2)
#bool_idx
#a[bool_idx]
a[[a > 2]]

c:\users\drt44888\documents\virtualenv\3_7venv\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


array([3, 4, 5, 6])

In [52]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)


print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))

print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


### Shape Manipulation

In [21]:
a = np.floor(10*np.random.random((3,4)))
print(a)

a.shape # returns the array, flattened

a.reshape(2,6)  # returns the array with a modified shape 

a.T  # returns the array, transposed

a.reshape(3,-1)

[[9. 7. 1. 7.]
 [8. 1. 2. 7.]
 [4. 2. 3. 7.]]


array([[9., 7., 1., 7.],
       [8., 1., 2., 7.],
       [4., 2., 3., 7.]])

### Functions and Methods Overview

###### Array Creation

arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like

######  Conversions

ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

######  Manipulations

array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

###### Questions
all, any, nonzero, where

###### Ordering

argmax, argmin, argsort, max, min, ptp, searchsorted, sort

######  Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

###### Basic Statistics
cov, mean, std, var

######  Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot

# Broadcasting rules

Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.

1 - If all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

2 - Arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension.

In [24]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x.shape)
v.shape

(4, 3)


(3,)

In [27]:
y = x + vv  # Add x and vv elementwise
print(y)  

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [ ]:
#Broadcasting

y = x + vv

### References:
    
https://docs.scipy.org/doc/numpy/user/index.html